apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-pvc
  namespace: frappe
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      app: frappe
