apiVersion: v1
kind: ConfigMap
metadata:
  name: frappe-sites
  namespace: frappe
data:
  config.yaml: |
    # Apps to install on the bench (bench get-app)
    apps:
      - name: crm
        url: https://github.com/FFX3/crm
        branch: main

    # Sites to create
    sites:
      - hostname: frappe.justinmcintyre.com
        db_name: justinm_db
        install_apps:
          - crm
