apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-server-pvc
  namespace: twenty
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      app: twenty-server
