# AUTO-GENERATED by setup-domains.sh - DO NOT EDIT MANUALLY
# Source: config/domains.yaml
# Regenerate by running: ./scripts/internal/setup-domains.sh

locals {
  # Subdomains from config/domains.yaml
  gen_subdomains = [
    "shell",
    "auth",
    "api",
    "studio",
    "crm",
    "matrix",
    "hermes",
    "passbolt",
    "webstudio",
    "test",
    "test2",
  ]
}
