apiVersion: ENC[AES256_GCM,data:Py0=,iv:QviVdXekvMoRfu7+dtza2SId7J7oud4SoPs29z7mFH8=,tag:5zCOUqNymFJnw8LbBtd6Uw==,type:str]
kind: ENC[AES256_GCM,data:P+o+02Mb,iv:qICWvQCEuO+fJgGBc3e+Mhm+tFhzcVpR4b0pcMcchAU=,tag:UIi86UcSzEdoOOLWzjyXYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:R1c9zf1QAybPqDNakuW96UcpWQM=,iv:RoAvgwbWm54UVR62Wcd+31Y8cuygaXjb9ZSUx3/FFqY=,tag:g+9PJybuvI1AktsnJ25Fvw==,type:str]
    namespace: ENC[AES256_GCM,data:KfGuJVe+CcA=,iv:AhAekGtnBJu27FJ19ofFjbbVoBVov0TbyZ1QuHYaV6c=,tag:DUBFi+8kP0G2h6jAyGUvgQ==,type:str]
type: ENC[AES256_GCM,data:+jsl2o3E,iv:kgylBOBy1dMHBKGPw8MCN26TSTBvs13tedSD25HO/6Y=,tag:Ghm/J7z38GPEeqi3YRsXEg==,type:str]
stringData:
    DATASOURCES_DEFAULT_URL: ENC[AES256_GCM,data:/RFtyBCLNUo6dd1hxXEjXWfNo9ol52Hs11s8wqRP/VZpU0EJmWS/vxFbXI//JgyV+xJVV3KkH0pjdglM5mfhY8Gh/4sCnAquEduWFZ16sjMXWdwFzwBALa1vA0/0,iv:n0iswlaBgYZpJXHXDnOyXgijet5Z5EbrT2npF3FjwAE=,tag:zv8GsE91iujJXQPDQ2ofPQ==,type:str]
    SECURITY_SALT: ENC[AES256_GCM,data:ap8xMsGMVTV3ZaOA20AukumYgbMfqCI80KsRFusME2J5qzVvTzng59gwQZ0=,iv:FeaZZFiLGdTgr+tI74rNsRZEzYxPhgCgzWx6COIQJMU=,tag:Dtrldu+Bdc0WQHBIY6DdpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb1JSYWswMFU3V1YxbWZq
            cG9xSUdaSzRvZUI2Q3JZVlJyTStjVG5WZ2hZCmQvWlpzQ08ySzZ0aHZwWndlRmNz
            UkNKUlhTNE9Bck5rR2hrNEJaV2VmM0UKLS0tIHRtVHNzdlJnNlFwd1FtSG9meWZK
            UU1RVURwdmZwY0J4U1MybW9NZktsaXcK9nvYFStOQF2DtrvjjV74JMzZxPsHZd73
            AXCxm9eoGLg1/ZVwBNWLGim1B1vkyBy1mXmabXU5g8DABBHVBcTHkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zu2flv3yyjxkh0qn77qgc5920prykqkhjq6862mxulfa6gn2sy2q5ah4zf
    lastmodified: "2026-08-24T16:41:22Z"
    mac: ENC[AES256_GCM,data:ocPIyxdmMYjyKccNb3WRGxJsynNewFmxfHWQJR4BexulQioVBY5m0irkYZG4lYKgd0gl6u8SRoL8XBle7UViJ6uAfE73AslPzn0fdbUPnKhzL9qRKFKaWTkMi48AF9SMDkgZB8mSov1PydPnDDpNLcV2U/AtC+OPn//wfRkNGe4=,iv:dos7bQFgTHrur32OWZBBgmWCvfqUkzOsk8SwNqvvCFQ=,tag:p86+GDHVcU4/qj5CKg2d4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
