apiVersion: ENC[AES256_GCM,data:NH4=,iv:SNouUthjfHShYhSGHKC/iUCITy10vZAhhiO03iAt8Iw=,tag:iIdwoBd0rZSefGOgxZ363w==,type:str]
kind: ENC[AES256_GCM,data:4WpeX4Yt,iv:9FL/QxRKDAYFR6Brk/HmfDFwXP5tKslv0IPetSbjYNQ=,tag:Anik+B21ru0RzvY+B0Z72g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:grjXrkNYKBHByIC5vSR3IE0=,iv:SDa/YWlPDHE+GXffYLdLtIwPzICmD+eTETS5bDrHtl4=,tag:nPi8JIyBacLilPlc8oPpIA==,type:str]
    namespace: ENC[AES256_GCM,data:e9I865I=,iv:LKAhmC/8sGJZJ5MO68phOhSMGEiFlqf3rhkulm5KhZI=,tag:i0wnDwtqalPNPu+cl5vbmA==,type:str]
type: ENC[AES256_GCM,data:iu8S0Or1,iv:2ULr8fSsgtGtBLIlPXlQdz6h3dAaC9Al0UydaWPRPho=,tag:VmsEbm9xgveEZw91tq7rXg==,type:str]
stringData:
    RESEND_API_KEY: ENC[AES256_GCM,data:JqpT6eqM6Shlbyhk2iEq8CBwvGVI08e/nRHtdA6w+wiT1Bc8,iv:P//57RqMNMvSEiPOWUXzHTtt0MhMtZ9cvlwuitCjhZ0=,tag:w1gDTr6SOItZhJZ58Hf27w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcGZwUDN4dHdUQXpRS3J4
            NjlhT1N4QkQ5TEMxYkxpUjZia2hIMFRmTmpNCmZ3OWJlOXVoeW9hdEFSZ1NVbU93
            S0RZbU5oMWtSQURsc1NiWng5UWtWUFUKLS0tIEVJb2VDTVc4Q2ZIcDFKeUpsb01j
            NmtrMUdtb3p2M2hJZ1N0bVJFTE1wVVUKaycqEvzxpR63Cd+4rtIZ/BH/bVTeG77n
            BY0TgS0PzTRQJLHnus+QCkzQleTuezfAkrkKD0LGLVifEeNoVFqxjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zu2flv3yyjxkh0qn77qgc5920prykqkhjq6862mxulfa6gn2sy2q5ah4zf
    lastmodified: "2026-08-24T17:42:44Z"
    mac: ENC[AES256_GCM,data:vSNcXnhQtVGns/zP6M26UbM7aiAQHqtyh6xUfoFPIBZlT37dOxUzXQZqj29rQzZdxAVBKn3ShckP6+Pk5rvuAhqlFpvrmYqGmNozFrB4cG/TlJYKTkgIYC1djy2/xH4yoJSwaMf4LhBogBIM75fsQy2lN1GiARTa/8+9BIF/LME=,iv:gWiFJxycQz7TlfxjYUopKN9dOBE+q/kI3hnuuHXLh6c=,tag:6DcvgmJXOQG846uEm3lQfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
