apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-app-2
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: test2.justinmcintyre.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-app-2
                port:
                  number: 80
