apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hermes
  namespace: hermes
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hermes.justinmcintyre.com
      secretName: hermes-tls
  rules:
    - host: hermes.justinmcintyre.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hermes
                port:
                  number: 9119
