apiVersion: ENC[AES256_GCM,data:MOU=,iv:+tXIoIxjLdcL4VWml6zpWqAF2rFP3lZHIOjvKrr8Or4=,tag:7nSCuiJZI7/44qNJZ1QhFw==,type:str]
kind: ENC[AES256_GCM,data:VtmDJOqf,iv:ukA1oETO0snhqIx5c2M4Byiic2R2zN02wrjmbFg1yPU=,tag:s91LpX/s6q706zgXbXz8jA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wIu2TuFJI2GUxlKyEgOgR1ze,iv:tzLta86EHDyq3cMUMLSXUjas3g0jo/qhJvLAyR5jG8Q=,tag:pS/eRpt7A2EFc4PAkuFkDw==,type:str]
    namespace: ENC[AES256_GCM,data:9qDupcl2,iv:7J2Ay6P+EvVehC9Rq6SUrra2ZQFzEMuR9w7k8jLc7XE=,tag:3d74+b4DKQzSwsn51HAESg==,type:str]
type: ENC[AES256_GCM,data:wnPmyAMN,iv:jeXlaO8GXehLcBF/IR4ZYcPhisecLuZm7Uq0b7UL+Zk=,tag:KDRTbLzM0SaXar4CFA2avw==,type:str]
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:eEbFce40oUtIbbA8wQTKcCBLUfr5mTvLKs0Khkv5E59Ggy/7rZQnlTHu0wPtbMTELb5hR2ua8njYUhvUigwkxwMVvA6tCqJNn2YBjxE+nnDFo9YrSjKGI0mTWUqFDg4gMDQk1KROBB4eMXzK,iv:oN/9bj8qJjzX7L1IEXimnO0WSA5v0y69sLVk9unZTjA=,tag:gFjQYUTGm3b06UKLkCWLzg==,type:str]
    PG_DATABASE_URL: ENC[AES256_GCM,data:xJnA0ehF35Z+/i1AoOK+pwtUK2/8oL1lefKlFrwuIExzLjlMw4gPvy7mKdiKNCb2XvY0n8zevexefLV/M+aDgvSJU66hnx8E2GFrv/ZEXn2U8LbVUABFy/YnqQ==,iv:Fdzt9toUo5CPPKtKTGpi/5y4xbuFvBDwVn67mda9Acw=,tag:b1ZadPkmiuT0Dm7GKUBn7A==,type:str]
    HERMES_DASHBOARD_OIDC_ISSUER: ENC[AES256_GCM,data:zfy6FeU/ZSYDZ2MN4ytUoQcoKGVF+tdHuBeyEbJ9Cw==,iv:vVUFuZsCBA8R11u03gY0g0knvoG+wgUuVlvV5nRzytE=,tag:/Yfzaj9bhwYx9MW5PeLy9g==,type:str]
    HERMES_DASHBOARD_OIDC_CLIENT_ID: ENC[AES256_GCM,data:XpHThO0cCgxoHz8GnsDTAw==,iv:wlRGSv1jpLWCGr5PwrdNrwZTXfEqOekZCyU+YOdnD60=,tag:I/tBdagwaTkFF1UgiY77+A==,type:str]
    HERMES_DASHBOARD_PUBLIC_URL: ENC[AES256_GCM,data:LpMHvtwg8L/n1DpJAdntqxyheruVFJ/Il17A/4Q82hQJ,iv:36KI5XA5LVIEpfS3PN5owgz7mQJgMiq/ZAIHSb4vVWg=,tag:dtHQfDxhzqeWZUm+ELa9Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNURQMG16Ylg0VmVGOFE4
            SWtHSnlhVnhmdTdaZE1rZHB2cWVDbXVZVnlNCnE5aExUL2szcy9JR05OWUZhL1Zp
            SkJTbjR4VFVEQWN3YWlzWmUrYlZYaHcKLS0tIDhYNCtXdVhuZG0xMWNzU2FhYUsv
            eUFYNktzUkJWejNNUTVGVzcyYjNiOTgKMdV7zBbwvGrjnZAmjfDXZBKoimgODJ+/
            cVlSxbVfrtkUR/bNHdd8fJ+EpR0wf0t3dQ+QmWC/wkw3Si1ZfGV69w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zu2flv3yyjxkh0qn77qgc5920prykqkhjq6862mxulfa6gn2sy2q5ah4zf
    lastmodified: "2026-06-30T17:07:02Z"
    mac: ENC[AES256_GCM,data:nqbydMnn9HGDivntOtaMGjyZRwIelMidd1S7QAaqvYsoGJCyireH8VUQjwe4giU7kxe0Dj/GfF5mULZXbGPK8f5Y9U/yM+/KctVSDRRGkDnca5Waq+u7TNMIizlqv41bPhtt71PaJeltZokvd4xeX3wZJ0+hkwhgfr7kyG3jXK0=,iv:TNVE2a5HnBMm2jM41St73J/u2ZY6zSobIKkjpM8f/W4=,tag:8BEUfNMU48F4NV20vHAfjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
