apiVersion: ENC[AES256_GCM,data:yC4=,iv:JYX2JZvz1pn0S3DW3xnjIBSb+MRXb28GwjLkWd0sqoA=,tag:T53IHiCr7OJlbZyNP2XUYg==,type:str]
kind: ENC[AES256_GCM,data:wt56GYBm,iv:1QJZj1EUrYHzU2rtWtYNiC0V4YC9wuJWs4Fi4CqqzFM=,tag:2OdL0ZW+JFhq5ek6gx0zoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8tPIwXiEFGleMW7ozfsu2fc+yTM=,iv:argK2/9D11XKDJYnYhBCRaacMnknuA9WoJ7KwCWWV9w=,tag:0awS5j5Dc9kb1qOXDXs2vg==,type:str]
    namespace: ENC[AES256_GCM,data:jXgCPzb43nw=,iv:VSdE6AsD0vYHes/AJiKzPEa+BJFR2EGjDEEEDWOT1Os=,tag:5v/nCBzWu80PVUK6T5TQiw==,type:str]
type: ENC[AES256_GCM,data:U3wLNDtV,iv:HDDSgLXPhTbKj1x1GDI4JWrqA3HNrShZOh3kATCtYhc=,tag:+TnGV8Ieitu6vc/oLcZhxA==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:te+gVGILZts=,iv:XwR1YTdKutkiATppkUWaPjrBKUhDIDl7j8RNf8o2DTU=,tag:1nI26KofJ3k9CRVfKum7xg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1Pw4s2PQiL9IYYZAFbM0HpPmZLTPanM0,iv:pNhYLF+T3F3XuQuO/ZRMY4FTwWWyyIL6SKnnBXv4EjA=,tag:JIK6fYviLYBUh+TcjfZWFQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:fAjNOI11H70=,iv:xLyCzDt1W5cFN+wdTGACt2GTrBw7oJps9tIxUvIUgJY=,tag:GGuBFjFEgLd8JHC9TNTKxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOXplSWFTZEk0aUYzTG9j
            Ky9QTkhDK2tOWDZtN0VhZ2I0eXF2OWVvL2tjCkRYVm1nV0JmZTBMdmg1a1VnWHV5
            K05YWFI2Rkh0VlJmRm9VQld0Yk9CVDgKLS0tIExtRUFwdndBcmxvWS9kd2hQWVMz
            MUQ5MG1rNWNvcEZWM25DSE1lK3dPc2MKf5v3pijILbYCu7vc8A1GJpifUObZuk9c
            e+DFFcFjp9RFFEXxlpUVV1CmyMpTT5076izIZzVF74Z/tvtGbfSFOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zu2flv3yyjxkh0qn77qgc5920prykqkhjq6862mxulfa6gn2sy2q5ah4zf
    lastmodified: "2026-06-02T16:05:36Z"
    mac: ENC[AES256_GCM,data:qcNoNnPOhEsnkrnDR1IVQtU4w8JKgfd/n+AGOlULNSh2azHY4dSIwMe2DMJHZkghuJUEOwD7NCVBEV7S4w7mA8nDba0wXT7RYg+FSQRJVwe71yIqnaiffFRrp2ysowKFNHhwxxsSQqgbYAin30RsE8+LzsWKxGSPs+kza9PE1jk=,iv:bfduRz31AbRxfL01ULjklYtLNqLCmYmLvvbA3jvBNTo=,tag:g7GWVB/3+cR02IGFEKC3dQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
