apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passbolt-pvc
  namespace: passbolt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
