apiVersion: v1
kind: PersistentVolume
metadata:
  name: command-center-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/mnt/data/command-center
