apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: command-center-pvc
  namespace: command-center
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
