apiVersion: v1
kind: Service
metadata:
  name: command-center
  namespace: command-center
spec:
  type: ClusterIP
  selector:
    app: command-center
  ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
