apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-pvc
  namespace: conduit
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      app: conduit
