apiVersion: ENC[AES256_GCM,data:lN4=,iv:M7UfQyhdxI+z57rofALjnQlZiVz5WWb0AL5emIpzNNI=,tag:1PJmrJtaP2B4P6blX/3o3A==,type:str]
kind: ENC[AES256_GCM,data:p7FLGHCD,iv:wpM4gKY4f0t34pPRWiXPaRpf/XYH11y4QjpQDhOkWZM=,tag:XUkAeXD5MosWI1JJsUxU5Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1jdHuSTGy0YS8tFK81jQv04ARQ==,iv:UuZShczJjtZYMudijw5gA0KTYzfePjPx3ev9Mz21NXA=,tag:JqdHQCuvVaSPLE3Q1KYqmA==,type:str]
    namespace: ENC[AES256_GCM,data:qhc+ka/7nA==,iv:rrMSPZoVLTjsqQ336IzhXfLe5WedBW2vPPBhi8D3ub0=,tag:Jh27jWoKFSOoyJp077869A==,type:str]
type: ENC[AES256_GCM,data:nQYxL9pu,iv:o441vwAM3VuivOBkK/tvrCtZey605n5zG7pqYwxKLeM=,tag:QsVpOg+hNtKnu8KfpEt+hg==,type:str]
stringData:
    CONDUIT_JWT_SECRET: ENC[AES256_GCM,data:gFWT6Ev0+1znQtCF+pRu6E7MacqDCcWSmLcolmPiHSwODktUwS9hPZX53F8=,iv:Rc1njWX5YbQ7q+7QmQhA70x+huzjPrZCiXJcPxdV3Xg=,tag:rO4Zc56Qb2t3d3w+0TS6SA==,type:str]
    CONDUIT_REGISTRATION_TOKEN: ENC[AES256_GCM,data:/PW8zThZF1XQVXrfmun3fUULM6Z0r8ihVwuIDM1AuZXVI1qLwOq0hG7R97o=,iv:Rafujehfsws7cg3d+qjE+O3oyqT+VBZ8hTi84/ZVDK0=,tag:KjAL6f1mWZWHyz2saPv9+A==,type:str]
    CONDUIT_EMERGENCY_PASSWORD: ENC[AES256_GCM,data:11zzpDwC65g6za+zYNBKlMcMvjtxAJozTVryBX0UaA2vWlZB99yYPDTwVs0=,iv:BiPKs3SWWdUpxCky6wmsTif7xtb+RSQPGZyjDxtHjKM=,tag:PSc8QZK2FClQvBFJljcvNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOWlEd291MU9YTlFseWlq
            d3p2cEdtYndESTR4Q3BVNUtBMXVENVJXTnhvClc2K2xMVjJ3cUI2aUt4RnlWckVW
            cEZ0OGtZOHlVazlWRE9odXVVbEdSMmcKLS0tIHh2TzYzdFQvME5nK090OE44bWNJ
            cUFGUDNpZm5MVWM4Vzh0bHl3Q3BuQXcKhydIdkG/wzKSyI2DVgZAVJaI1XghQYMZ
            ll4iU8BKCpCwQibtCDMDY0tvptbFileto+RpiP4k2Vh9wY6CZNLZ+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zu2flv3yyjxkh0qn77qgc5920prykqkhjq6862mxulfa6gn2sy2q5ah4zf
    lastmodified: "2026-06-17T19:09:23Z"
    mac: ENC[AES256_GCM,data:eI1PnZcT+38bG75vQGKsySeXAf0ayBABM+R/setsx/QfudMPG9MpyyFbj38ie3hJxjmXn+rtY8MoFR2jVjj6XolIjw2hFHTf4MGGHtU+4Pm9WAJ6HmuTaPGCud4P3ebK/38l94caDEPtIfH8Yy77LsZOerGxXmb6vYbNzxxfscY=,iv:ZWhJTBX7Dzq5aiCFJbWdkApVeIyVTWlrHVt3XAnuSHQ=,tag:oTrsGcj/b3agstD7EJp3yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
