apiVersion: ENC[AES256_GCM,data:G0c=,iv:Oo5WmV1JMDb3Ft1lcjbUW3EH9nBEbLVBZZs1f+4eW1Q=,tag:MdSn0pZ7JTvsISEbfQM1gA==,type:str]
kind: ENC[AES256_GCM,data:W1oN1/n7,iv:vQEmuK0X76fz39OgZXjqWkas0OvkU47lQ1k+cC4137s=,tag:/papJm47uLG3jsgxZpQy3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ie0WvEobdwae+PmE0U7xyU/n,iv:WG7hrnRbODjBxfh5hOhhAz+3YLRu3n02mEpv3v76yso=,tag:pGr95khIOeusfSkOkOgvIA==,type:str]
    namespace: ENC[AES256_GCM,data:pCU8tRDr,iv:d9cCTDoZomkEIy897ZdQAlkZfo1qusss9tCxU19k7Vc=,tag:rf6vdhxOAKs4MA7wpivsBA==,type:str]
type: ENC[AES256_GCM,data:8nBylkzX,iv:38ZT9KM8mQMiX57LhHhjeBTCixqHEFTfj1eVadCvjV4=,tag:z90tm1k36AqH/JT+VsRVHw==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:QuiwnDhu/UJbkhNBFJ54tzhaze25pF8oQHU7L8Iiq1+tIpsZSDMFER540IVPbf05z7CppSUOaxD7/u9wjXn/O/F67Tn06Hl+g5JcuZw/7Y0dxTrBbQWLkjMeWStWxU1Hw8lWzpyejMkpKqIQOHPJRULfUeN1zCcrpuk39dCL1gp87a1c,iv:E5fkIzWfd8ms1wMUs9TL9UQK9P9tPu96Lg0kC5EGCcA=,tag:yY4LooBBSgl+WdDvmsSjTg==,type:str]
    GOTRUE_JWT_SECRET: ENC[AES256_GCM,data:GtlasrnfGsq0LR3iH988zKvM7wywKC7Cwidh3qKyrg2mBjsYXMWIff4fSoM=,iv:IL5npzdVirRJAxgC9vifvWdwOzwHapJJ60YlVFSFgc0=,tag:C0j9yOoRliy1x3uT9E+AQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdFBLZWo1YzVWSDhORDVv
            c3Uyd2xHZnRlWXFJYkU5RHdzRzlPRzF4bUNBCkE5WU5ram54MDAya081WmJqMnpP
            R0V0NjR0b2VkbFJmOTJndTFzS2dGWDQKLS0tIDNUZjBnemU4c0pHZWFUczRnTTJt
            K0pPOW1zK0M3ajhjNHRjc0VWVHRQamMKvVt9A7zKZdd3wVRs2q6HzP9vdgJKx5Gj
            6XjzvD0vftdxcCSwmETA5UZlHSKWTxDxkDuEBHgReUtwRj4EDnzAlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zu2flv3yyjxkh0qn77qgc5920prykqkhjq6862mxulfa6gn2sy2q5ah4zf
    lastmodified: "2026-06-30T20:14:38Z"
    mac: ENC[AES256_GCM,data:hVHHtafV2lnLadqQ0wGwWNCNNBcJNQ1el4N/eByuokMIbXGBlg0g9Cn8kUiV7Ar6g2246U1Lq4KaZrGquQQXGsr05nuN+TK+sUNFcj8W3F719go4KZ104bsW/msW1ZUn1UlDwcztaB0aYi4qKyA/GjbxhEDFrA5odNr1ikHPFbU=,iv:tRM7TfFEGa6pWvmhygq/C5OwTd2a88o5oYhpkY+7CG8=,tag:GM/vKhtQkfTrZOS11XwINw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
