apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webstudio-minio-pvc
  namespace: webstudio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local
      app: webstudio-minio
