#!/usr/bin/env bash
# Centralized domain setup script
# Reads config/domains.yaml and ensures DNS + certs are configured
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(dirname "$(dirname "$SCRIPT_DIR")")}"
CONFIG_FILE="$ROOT_DIR/config/domains.yaml"
TERRAFORM_DIR="$ROOT_DIR/terraform/compute"
CERTS_DIR="$ROOT_DIR/certs"

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Error: $CONFIG_FILE not found"
    exit 1
fi

# Get base domain
BASE_DOMAIN=$(yq '.domain' "$ROOT_DIR/config/domain.yaml")

echo "Domain setup for: $BASE_DOMAIN"
echo ""

# Extract subdomain names from config
SUBDOMAINS=$(yq '.subdomains[].name' "$CONFIG_FILE")
SUBDOMAIN_COUNT=$(yq '.subdomains | length' "$CONFIG_FILE")

echo "Configured subdomains ($SUBDOMAIN_COUNT):"
for sub in $SUBDOMAINS; do
    echo "  - $sub.$BASE_DOMAIN"
done
echo ""

# Generate terraform subdomains list
echo "Generating terraform configuration..."
GEN_TF_FILE="$TERRAFORM_DIR/gen-subdomains.tf"

cat > "$GEN_TF_FILE" << 'HEADER'
# AUTO-GENERATED by setup-domains.sh - DO NOT EDIT MANUALLY
# Source: config/domains.yaml
# Regenerate by running: ./scripts/internal/setup-domains.sh

locals {
  # Subdomains from config/domains.yaml
  gen_subdomains = [
HEADER

for sub in $SUBDOMAINS; do
    echo "    \"$sub\"," >> "$GEN_TF_FILE"
done

cat >> "$GEN_TF_FILE" << 'FOOTER'
  ]
}
FOOTER

echo "  Created: $GEN_TF_FILE"

# Check if cloudflare.tf uses gen_subdomains
if grep -q "local.subdomains" "$TERRAFORM_DIR/cloudflare.tf" 2>/dev/null; then
    echo ""
    echo "WARNING: cloudflare.tf still uses 'local.subdomains'"
    echo "Update it to use 'local.gen_subdomains' instead:"
    echo "  for_each = toset(local.gen_subdomains)"
fi

# Check for missing cert backups
echo ""
echo "Checking cert backups..."
MISSING_CERTS=()
for sub in $SUBDOMAINS; do
    CERT_FILE="$CERTS_DIR/${sub}-tls.enc.yaml"
    if [[ ! -f "$CERT_FILE" ]]; then
        MISSING_CERTS+=("$sub")
    fi
done

if [[ ${#MISSING_CERTS[@]} -gt 0 ]]; then
    echo "Missing cert backups (will be created by cert-manager):"
    for sub in "${MISSING_CERTS[@]}"; do
        echo "  - $sub-tls.enc.yaml"
    done
    echo ""
    echo "To backup certs after deployment:"
    echo "  ./scripts/internal/backup-certs.sh"
else
    echo "  All cert backups present"
fi

echo ""
echo "Domain setup complete."
echo ""
echo "Next steps:"
echo "  1. Review $GEN_TF_FILE"
echo "  2. Update cloudflare.tf to use local.gen_subdomains"
echo "  3. Run: cd terraform/compute && terraform apply"
