#!/usr/bin/env bash
# Centralized database setup script
# Reads config/databases.yaml and creates databases/users from sops-encrypted secrets
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(dirname "$(dirname "$SCRIPT_DIR")")}"
CONFIG_FILE="$ROOT_DIR/config/databases.yaml"

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Error: $CONFIG_FILE not found"
    exit 1
fi

# Check postgres is running
if ! kubectl get statefulset postgres -n postgres &>/dev/null; then
    echo "Error: PostgreSQL must be deployed first"
    exit 1
fi

# Read URL pattern from config
URL_PATTERN=$(yq '.url_pattern' "$CONFIG_FILE")

# Get number of databases
DB_COUNT=$(yq '.databases | length' "$CONFIG_FILE")

echo "Setting up $DB_COUNT databases..."

for ((i=0; i<DB_COUNT; i++)); do
    DB_NAME=$(yq ".databases[$i].name" "$CONFIG_FILE")
    CONFIG_PATH=$(yq ".databases[$i].config_path" "$CONFIG_FILE")
    SCHEMA=$(yq ".databases[$i].schema // \"\"" "$CONFIG_FILE")

    SECRET_FILE="$ROOT_DIR/$CONFIG_PATH/secret.enc.yaml"

    if [[ ! -f "$SECRET_FILE" ]]; then
        echo "  Warning: $SECRET_FILE not found, skipping $DB_NAME"
        continue
    fi

    echo "  Processing: $DB_NAME"

    # Decrypt and extract DATABASE_URL
    DECRYPTED=$(sops --decrypt "$SECRET_FILE" 2>/dev/null) || {
        echo "    Error: Failed to decrypt $SECRET_FILE"
        continue
    }

    # Find line matching the URL pattern and extract the URL
    DB_URL=$(echo "$DECRYPTED" | grep -E "$URL_PATTERN" | head -1 | sed 's/.*: *//' | tr -d '"' | tr -d "'")

    if [[ -z "$DB_URL" ]]; then
        echo "    Warning: No DATABASE_URL found matching pattern '$URL_PATTERN'"
        continue
    fi

    # Parse URL: postgres://user:password@host:port/database
    # Extract user and password
    USER=$(echo "$DB_URL" | sed -n 's|.*://\([^:]*\):.*|\1|p')
    PASSWORD=$(echo "$DB_URL" | sed -n 's|.*://[^:]*:\([^@]*\)@.*|\1|p')

    if [[ -z "$USER" || -z "$PASSWORD" ]]; then
        echo "    Warning: Could not parse user/password from URL"
        continue
    fi

    # Create user if not exists
    EXISTS=$(kubectl exec -n postgres statefulset/postgres -- psql -U postgres -t -c \
        "SELECT 1 FROM pg_roles WHERE rolname='$USER'" 2>/dev/null | tr -d ' ')

    if [[ "$EXISTS" != "1" ]]; then
        kubectl exec -n postgres statefulset/postgres -- psql -U postgres -c \
            "CREATE USER $USER WITH ENCRYPTED PASSWORD '$PASSWORD'" &>/dev/null
        echo "    Created user: $USER"
    else
        echo "    User exists: $USER"
    fi

    # Handle schema-based setup (like GoTrue)
    if [[ -n "$SCHEMA" && "$SCHEMA" != "null" ]]; then
        echo "    Setting up schema: $SCHEMA"
        kubectl exec -n postgres statefulset/postgres -- psql -U postgres -c \
            "CREATE EXTENSION IF NOT EXISTS pgcrypto" &>/dev/null
        kubectl exec -n postgres statefulset/postgres -- psql -U postgres -c \
            "CREATE SCHEMA IF NOT EXISTS $SCHEMA AUTHORIZATION $USER" &>/dev/null
        kubectl exec -n postgres statefulset/postgres -- psql -U postgres -c \
            "GRANT ALL ON SCHEMA $SCHEMA TO $USER" &>/dev/null
    else
        # Create database if not exists
        DB_EXISTS=$(kubectl exec -n postgres statefulset/postgres -- psql -U postgres -t -c \
            "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" 2>/dev/null | tr -d ' ')

        if [[ "$DB_EXISTS" != "1" ]]; then
            kubectl exec -n postgres statefulset/postgres -- psql -U postgres -c \
                "CREATE DATABASE $DB_NAME OWNER $USER" &>/dev/null
            echo "    Created database: $DB_NAME"
        else
            echo "    Database exists: $DB_NAME"
        fi

        # Grant permissions on public schema
        kubectl exec -n postgres statefulset/postgres -- psql -U postgres -d "$DB_NAME" -c \
            "GRANT ALL ON SCHEMA public TO $USER" &>/dev/null
    fi

    # Generate PostgREST secret if enabled for this database
    POSTGREST_ENABLED=$(yq ".databases[$i].postgrest // false" "$CONFIG_FILE")
    if [[ "$POSTGREST_ENABLED" == "true" ]]; then
        echo "    Generating PostgREST secret: gen-postgrest-$DB_NAME-credentials"

        # Build the internal DATABASE_URL (pointing to postgres service in postgres namespace)
        INTERNAL_DB_URL="postgres://$USER:$PASSWORD@postgres.postgres.svc.cluster.local:5432/$DB_NAME"

        # Create/update the secret in platform-services namespace
        kubectl apply -f - <<EOF
# AUTO-GENERATED by setup-databases.sh - DO NOT EDIT MANUALLY
# Source: $CONFIG_PATH/secret.enc.yaml
# Regenerate by running: ./scripts/internal/setup-databases.sh
apiVersion: v1
kind: Secret
metadata:
  name: gen-postgrest-$DB_NAME-credentials
  namespace: platform-services
  labels:
    generated-by: setup-databases
    source-database: $DB_NAME
  annotations:
    setup-databases.sh/generated: "true"
    setup-databases.sh/source: "$CONFIG_PATH/secret.enc.yaml"
type: Opaque
stringData:
  DATABASE_URL: "$INTERNAL_DB_URL"
EOF
    fi
done

echo "Database setup complete."
