apiVersion: v1
kind: Service
metadata:
  name: cloudflare-publisher
  namespace: webstudio
spec:
  selector:
    app: cloudflare-publisher
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
